### ISSUE TITLE
折腾了WR703N很久了，没有进展

### ISSUE THREAD

**Issue by meloncloud** [blueveryday/lede_WR703Nv1#1]
这个能编译么？WR703N折腾了很久，没有什么进展。刷入后总是自动无限重启。

**Comment by blueveryday** [comment]
我这个云编译是可以用的。
你可以直接下载Actions里面已经编译好的固件包。

**Comment by blueveryday** [comment]
> 这个能编译么？WR703N折腾了很久，没有什么进展。刷入后总是自动无限重启。

这个是云编译的，从actions里面下载编译好的文件即可。

**Comment by meloncloud** [comment]
折腾了好久云编译都没有成功，再试试你这个。想编译一个其他的路由器固件也可以用你的脚本吧？

**Comment by blueveryday** [comment]
> 折腾了好久云编译都没有成功，再试试你这个。想编译一个其他的路由器固件也可以用你的脚本吧？

703没有问题，我都用上了。
其他机型需要修改配置文件config，自己研究吧。

**Comment by meloncloud** [comment]
好的，谢谢你的仓库。我自己试着再编译其他的固件吧。
